version: 0.2  
 
phases:
 build:
   commands: 
      - echo "Connecting to ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n4j8z6s4
      - docker build -t flask-hello-world .
      - echo "Container build successfully"
      - docker tag flask-hello-world:latest public.ecr.aws/n4j8z6s4/flask-hello-world:latest
      - docker push public.ecr.aws/n4j8z6s4/flask-hello-world:latest
      - echo "Container Successfully pushed to ECR"
      - apt-get install jq -y
      - ContainerName="flask-hello-world"
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - printf '[{"name":"CONTAINER_NAME","imageUri":"IMAGE_URI"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$ContainerName|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_URI|$ImageURI|g" imagedefinitions.json
      - cat imagedefinitions.json
      
artifacts:
    files:
        - imagedefinitions.json
