version: 0.2  
 
phases:
 build:
   commands: 
      - echo "Connecting to ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n4j8z6s4
      - docker build -t flask-hello-world .
      - echo "Container build successfully"
      - docker tag flask-hello-world:latest public.ecr.aws/n4j8z6s4/flask-hello-world:latest
      - docker push public.ecr.aws/n4j8z6s4/flask-hello-world:latest
      - echo "Container Successfully pushed to ECR"
      - apt-get install jq -y
      - ContainerName="flask-hello-world"
      - PHP_REPOSITORY_URI=$(cat imageDetail.json | python -c "import sys, json; print(json.load(sys.stdin)['ImageURI'].split('@')[0])")
      - IMAGE_TAG=$(cat imageDetail.json | python -c "import sys, json; print(json.load(sys.stdin)['ImageTags'][0])")
      - echo $PHP_REPOSITORY_URI:$IMAGE_TAG

    
 post_build:
    commands:
      - echo Writing image definitions file...
      - ImageURI=$(cat imageDetail.json | jq -r '.ImageURI')
      - printf '[{"name":"container","imageUri":"%s"}]' $PHP_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      
artifacts:
    files:
        - imagedefinitions.json
