version: 0.2  
 
phases:
 build:
   commands:  
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 298495439718.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t flask-hello-world .
      - docker tag flask-hello-world:latest 298495439718.dkr.ecr.ap-south-1.amazonaws.com/flask-hello-world:latest
      - docker push 298495439718.dkr.ecr.ap-south-1.amazonaws.com/flask-hello-world:latest
